[package]
name = "sunshine-resolution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displayz = "0.1.0"
config = "0.14.0"